// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package dbgen

import (
	"context"
)

const addTagToTask = `-- name: AddTagToTask :exec
INSERT OR IGNORE INTO task_tags (task_id, tag_id) VALUES (?, ?)
`

type AddTagToTaskParams struct {
	TaskID int64 `json:"task_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddTagToTask(ctx context.Context, arg AddTagToTaskParams) error {
	_, err := q.db.ExecContext(ctx, addTagToTask, arg.TaskID, arg.TagID)
	return err
}

const countTasksByProject = `-- name: CountTasksByProject :one
SELECT COUNT(*) FROM tasks WHERE project_id = ?
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, body, status, due_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, title, body, status, due_at, created_at, updated_at, done_at
`

type CreateTaskParams struct {
	ProjectID int64  `json:"project_id"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Status    string `json:"status"`
	DueAt     *int64 `json:"due_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ? AND project_id = ?
`

type DeleteTaskParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.ProjectID)
	return err
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT (name) DO UPDATE SET name = excluded.name
RETURNING id, name, created_at
`

func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, created_at FROM projects WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, created_at FROM projects WHERE name = ?
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.id = ? AND t.project_id = ?
`

type GetTaskParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

type GetTaskRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.ProjectID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneAt,
		&i.ProjectName,
	)
	return i, err
}

const listOverdueTasks = `-- name: ListOverdueTasks :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.project_id = ? AND t.status = 'open' AND t.due_at < unixepoch()
ORDER BY t.due_at ASC
`

type ListOverdueTasksRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) ListOverdueTasks(ctx context.Context, projectID int64) ([]ListOverdueTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueTasksRow{}
	for rows.Next() {
		var i ListOverdueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, created_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTask = `-- name: ListTagsForTask :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN task_tags tt ON t.id = tt.tag_id
WHERE tt.task_id = ?
ORDER BY t.name
`

func (q *Queries) ListTagsForTask(ctx context.Context, taskID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.project_id = ?
ORDER BY
    CASE WHEN t.status = 'open' THEN 0 ELSE 1 END,
    t.created_at DESC
`

type ListTasksRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) ListTasks(ctx context.Context, projectID int64) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByTag = `-- name: ListTasksByTag :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN task_tags tt ON t.id = tt.task_id
JOIN tags tg ON tt.tag_id = tg.id
WHERE t.project_id = ? AND tg.name = ?
ORDER BY t.created_at DESC
`

type ListTasksByTagParams struct {
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
}

type ListTasksByTagRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) ListTasksByTag(ctx context.Context, arg ListTasksByTagParams) ([]ListTasksByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByTag, arg.ProjectID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByTagRow{}
	for rows.Next() {
		var i ListTasksByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksDone = `-- name: ListTasksDone :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.project_id = ? AND t.status = 'done'
ORDER BY t.done_at DESC
`

type ListTasksDoneRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) ListTasksDone(ctx context.Context, projectID int64) ([]ListTasksDoneRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksDone, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksDoneRow{}
	for rows.Next() {
		var i ListTasksDoneRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksOpen = `-- name: ListTasksOpen :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.project_id = ? AND t.status = 'open'
ORDER BY t.created_at DESC
`

type ListTasksOpenRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) ListTasksOpen(ctx context.Context, projectID int64) ([]ListTasksOpenRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksOpen, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksOpenRow{}
	for rows.Next() {
		var i ListTasksOpenRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksWithDue = `-- name: ListTasksWithDue :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.project_id = ? AND t.due_at IS NOT NULL
ORDER BY t.due_at ASC
`

type ListTasksWithDueRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) ListTasksWithDue(ctx context.Context, projectID int64) ([]ListTasksWithDueRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksWithDue, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksWithDueRow{}
	for rows.Next() {
		var i ListTasksWithDueRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskDone = `-- name: MarkTaskDone :one
UPDATE tasks SET
    status = 'done',
    done_at = unixepoch(),
    updated_at = unixepoch()
WHERE id = ? AND project_id = ?
RETURNING id, project_id, title, body, status, due_at, created_at, updated_at, done_at
`

type MarkTaskDoneParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, markTaskDone, arg.ID, arg.ProjectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneAt,
	)
	return i, err
}

const markTaskOpen = `-- name: MarkTaskOpen :one
UPDATE tasks SET
    status = 'open',
    done_at = NULL,
    updated_at = unixepoch()
WHERE id = ? AND project_id = ?
RETURNING id, project_id, title, body, status, due_at, created_at, updated_at, done_at
`

type MarkTaskOpenParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) MarkTaskOpen(ctx context.Context, arg MarkTaskOpenParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, markTaskOpen, arg.ID, arg.ProjectID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneAt,
	)
	return i, err
}

const removeAllTagsFromTask = `-- name: RemoveAllTagsFromTask :exec
DELETE FROM task_tags WHERE task_id = ?
`

func (q *Queries) RemoveAllTagsFromTask(ctx context.Context, taskID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllTagsFromTask, taskID)
	return err
}

const removeTagFromTask = `-- name: RemoveTagFromTask :exec
DELETE FROM task_tags WHERE task_id = ? AND tag_id = ?
`

type RemoveTagFromTaskParams struct {
	TaskID int64 `json:"task_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromTask(ctx context.Context, arg RemoveTagFromTaskParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTask, arg.TaskID, arg.TagID)
	return err
}

const searchTasksLike = `-- name: SearchTasksLike :many
SELECT t.id, t.project_id, t.title, t.body, t.status, t.due_at, t.created_at, t.updated_at, t.done_at, p.name as project_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
WHERE t.project_id = ?
  AND (t.title LIKE '%' || ? || '%' OR t.body LIKE '%' || ? || '%')
ORDER BY t.created_at DESC
`

type SearchTasksLikeParams struct {
	ProjectID int64   `json:"project_id"`
	Column2   *string `json:"column_2"`
	Column3   *string `json:"column_3"`
}

type SearchTasksLikeRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	Title       string `json:"title"`
	Body        string `json:"body"`
	Status      string `json:"status"`
	DueAt       *int64 `json:"due_at"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
	DoneAt      *int64 `json:"done_at"`
	ProjectName string `json:"project_name"`
}

func (q *Queries) SearchTasksLike(ctx context.Context, arg SearchTasksLikeParams) ([]SearchTasksLikeRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTasksLike, arg.ProjectID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTasksLikeRow{}
	for rows.Next() {
		var i SearchTasksLikeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topTagsForProject = `-- name: TopTagsForProject :many
SELECT tg.name, COUNT(*) as usage_count
FROM tags tg
JOIN task_tags tt ON tg.id = tt.tag_id
JOIN tasks t ON tt.task_id = t.id
WHERE t.project_id = ?
GROUP BY tg.id
ORDER BY usage_count DESC
LIMIT ?
`

type TopTagsForProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int64 `json:"limit"`
}

type TopTagsForProjectRow struct {
	Name       string `json:"name"`
	UsageCount int64  `json:"usage_count"`
}

func (q *Queries) TopTagsForProject(ctx context.Context, arg TopTagsForProjectParams) ([]TopTagsForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, topTagsForProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopTagsForProjectRow{}
	for rows.Next() {
		var i TopTagsForProjectRow
		if err := rows.Scan(&i.Name, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title = COALESCE(?3, title),
    body = COALESCE(?4, body),
    due_at = CASE WHEN ?5 = 1 THEN NULL ELSE COALESCE(?6, due_at) END,
    updated_at = unixepoch()
WHERE id = ? AND project_id = ?
RETURNING id, project_id, title, body, status, due_at, created_at, updated_at, done_at
`

type UpdateTaskParams struct {
	Title     *string     `json:"title"`
	Body      *string     `json:"body"`
	ClearDue  interface{} `json:"clear_due"`
	DueAt     *int64      `json:"due_at"`
	ID        int64       `json:"id"`
	ProjectID int64       `json:"project_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Body,
		arg.ClearDue,
		arg.DueAt,
		arg.ID,
		arg.ProjectID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneAt,
	)
	return i, err
}
